version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000' # local machine : container
    volumes:
      - /app/node_modules # use location in container
      - .:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # use location in container
      - .:/app
    command: ["npm", "run", "test"]